import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { configure, parseArgs, validateKey } from './configure-linear.mjs';

const KEY = 'lin_api_synthetic_secret_key_value_1234';
const ideation = { enabled: true, backlogCap: 10, batchSize: 3, minimumIntervalHours: 24, ideaLabel: 'Idea', proposedState: 'Backlog', approvedState: 'Todo', rejectedState: 'Canceled' };

function fixture(t, { manifest = {} } = {}) {
  const root = mkdtempSync(path.join(os.tmpdir(), 'configure-linear-')); t.after(() => rmSync(root, { recursive: true, force: true }));
  const home = path.join(root, 'home'); const checkout = path.join(root, 'checkout'); const toolkit = path.join(root, 'kit');
  const configDir = path.join(home, '.config/agent-team'); const unitDir = path.join(home, '.config/systemd/user');
  mkdirSync(configDir, { recursive: true, mode: 0o700 }); mkdirSync(unitDir, { recursive: true }); mkdirSync(checkout); mkdirSync(toolkit);
  writeFileSync(path.join(configDir, 'worker.json'), JSON.stringify({ coordinatorUrl: 'http://127.0.0.1:4310', workerId: 'x3d', projects: { myntbase: checkout } }), { mode: 0o600 });
  writeFileSync(path.join(configDir, 'service.env'), 'AGENT_TEAM_TOKEN=x\nPATH="/bin"\n', { mode: 0o600 });
  writeFileSync(path.join(unitDir, 'agent-team-worker.service'), '[Service]\n', { mode: 0o600 });
  writeFileSync(path.join(unitDir, 'agent-team-dashboard.service'), '[Service]\n', { mode: 0o600 });
  writeFileSync(path.join(checkout, '.agent-team.json'), JSON.stringify({ queueProjectId: 'myntbase', workspaceId: 'w', teamId: 't', projectId: 'p', readyLabel: 'agent:ready', ideation, ...manifest }));
  const logs = []; const contexts = []; let apiKey;
  const linear = options => { apiKey = options.apiKey; return { context: async manifest => { contexts.push(manifest.queueProjectId); if (manifest.workspaceId === 'wrong') throw new Error('Linear workspace mismatch'); } }; };
  return { home, toolkit, configDir, unitDir, logs, contexts, key: () => apiKey,
    run: (extra = {}) => configure({ home, toolkit, nodePath: '/opt/node', keySource: async () => `${KEY}\n`, linear, log: line => logs.push(line), ...extra }) };
}

test('CLI options and key validation', () => {
  assert.deepEqual(parseArgs([]), {});
  assert.equal(parseArgs(['--install']).install, true);
  assert.equal(parseArgs(['--dry-run', '--key-file', '/private/key']).keyFile, '/private/key');
  for (const args of [['--install', '--dry-run'], ['--key-file'], ['--other']]) assert.throws(() => parseArgs(args));
  assert.equal(validateKey(` ${KEY} `), KEY);
  for (const key of ['short', 'has space in it and is long enough', 'bad$chars_but_long_enough_value', undefined]) assert.throws(() => validateKey(key), /Linear API key/);
});

test('dry-run validates every project against Linear and writes nothing', async t => {
  const f = fixture(t);
  const result = await f.run();
  assert.equal(result.installed, false); assert.deepEqual(result.projects, ['myntbase']);
  assert.deepEqual(f.contexts, ['myntbase']); assert.equal(f.key(), KEY);
  assert.deepEqual(readdirSync(f.configDir).sort(), ['service.env', 'worker.json']);
  assert.deepEqual(readdirSync(f.unitDir).sort(), ['agent-team-dashboard.service', 'agent-team-worker.service']);
  assert.ok(!f.logs.join('\n').includes(KEY));
  assert.deepEqual(f.logs.slice(-3), ['systemctl --user daemon-reload', 'systemctl --user restart agent-team-worker.service agent-team-dashboard.service', 'systemctl --user start agent-team-intake.service']);
});

test('installation writes private key, intake config, unit and worker drop-in without starting anything', async t => {
  const f = fixture(t);
  const result = await f.run({ install: true });
  assert.equal(result.installed, true);
  for (const file of result.paths) assert.equal(statSync(file).mode & 0o777, 0o600);
  assert.equal(readFileSync(path.join(f.configDir, 'linear.env'), 'utf8'), `LINEAR_API_KEY=${KEY}\n`);
  const intake = JSON.parse(readFileSync(path.join(f.configDir, 'intake.json'), 'utf8'));
  assert.deepEqual(intake, { coordinatorUrl: 'http://127.0.0.1:4310', pollSeconds: 60, projects: { myntbase: path.join(path.dirname(f.home), 'checkout') } });
  const unit = readFileSync(path.join(f.unitDir, 'agent-team-intake.service'), 'utf8');
  assert.ok(unit.includes(`ExecStart="/opt/node" "${f.toolkit}/linear-intake.mjs" --config "${f.configDir}/intake.json"`));
  assert.ok(unit.includes(`EnvironmentFile=${f.configDir}/linear.env\n`) && !unit.includes('[Install]') && !unit.includes(KEY));
  for (const unit of ['worker', 'dashboard']) assert.equal(readFileSync(path.join(f.unitDir, `agent-team-${unit}.service.d/linear.conf`), 'utf8'), `# Generated by agent-team configure-linear.mjs v1\n[Service]\nEnvironmentFile=${f.configDir}/linear.env\n`);
  assert.ok(!f.logs.join('\n').includes(KEY));
  // Rotation replaces the key file only; other generated files must be identical.
  const rotated = 'lin_api_synthetic_rotated_key_value_5678';
  await f.run({ install: true, keySource: async () => rotated });
  assert.equal(readFileSync(path.join(f.configDir, 'linear.env'), 'utf8'), `LINEAR_API_KEY=${rotated}\n`);
  writeFileSync(path.join(f.unitDir, 'agent-team-intake.service'), 'edited by hand\n', { mode: 0o600 });
  await assert.rejects(f.run({ install: true }), /Refusing to replace differing file/);
});

test('validation failures, missing installation and malformed manifests write nothing and never echo the key', async t => {
  const wrong = fixture(t, { manifest: { workspaceId: 'wrong' } });
  await assert.rejects(wrong.run({ install: true }), error => /Linear validation failed for myntbase/.test(error.message) && !error.message.includes(KEY));
  assert.deepEqual(readdirSync(wrong.configDir).sort(), ['service.env', 'worker.json']);
  const mismatch = fixture(t, { manifest: { queueProjectId: 'other' } });
  await assert.rejects(mismatch.run({ install: true }), /queueProjectId/);
  const disabled = fixture(t, { manifest: { ideation: { ...ideation, enabled: false } } });
  await assert.rejects(disabled.run({ install: true }), /Ideation/);
  const bare = fixture(t);
  rmSync(path.join(bare.unitDir, 'agent-team-worker.service'));
  await assert.rejects(bare.run({ install: true }), /Worker service unit/);
  assert.equal(bare.contexts.length, 0);
  const invalid = fixture(t);
  await assert.rejects(invalid.run({ keySource: async () => 'nope' }), /Linear API key/);
  assert.equal(invalid.contexts.length, 0);
});
