import { mkdirSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { atomicWrite, clean, inspect, privateDirectory, quote, readExisting } from './install-local.mjs';
import { createLinearClient } from '../../tracker/linear.mjs';
import { validateIdeation } from '../../../core/idea-schema.mjs';

const toolkitRoot = path.dirname(path.dirname(path.dirname(path.dirname(fileURLToPath(import.meta.url)))));
const url = 'http://127.0.0.1:4310';
const usage = 'Usage: configure-linear.mjs [--key-file /absolute/private/file] [--dry-run | --install]';

export function parseArgs(args) {
  const options = {}; const seen = new Set();
  for (let i = 0; i < args.length; i++) {
    const flag = args[i];
    if (seen.has(flag)) throw new Error(usage);
    seen.add(flag);
    if (flag === '--install' || flag === '--dry-run') options.install = flag === '--install';
    else if (flag === '--key-file' && args[i + 1] && !args[i + 1].startsWith('--')) options.keyFile = args[++i];
    else throw new Error(usage);
  }
  if (seen.has('--install') && seen.has('--dry-run')) throw new Error(usage);
  return options;
}

// Linear personal keys are URL-safe tokens; anything else is rejected before it can reach a file.
export function validateKey(key) {
  if (typeof key !== 'string' || !/^[A-Za-z0-9_-]{20,256}$/.test(key.trim())) throw new Error('Expected a Linear API key of 20 to 256 URL-safe characters');
  return key.trim();
}

function json(file) {
  const text = readExisting(file);
  if (text === null) throw new Error(`Missing ${file}; run install-local.mjs first`);
  try { return JSON.parse(text); } catch { throw new Error(`Invalid JSON config: ${file}`); }
}

// Dependency injection is API-only; the CLI always uses the actual user, key source and Linear.
export async function configure({ keySource, install: write = false, home = homedir(), toolkit = toolkitRoot,
  nodePath = process.execPath, linear = createLinearClient, log = console.log } = {}) {
  if (process.platform !== 'linux') throw new Error('Local installation requires Linux');
  home = path.normalize(clean(home)); toolkit = path.normalize(clean(toolkit)); nodePath = path.normalize(clean(nodePath));
  const configDir = path.join(home, '.config/agent-team');
  const unitDir = path.join(home, '.config/systemd/user');
  const dropinDir = path.join(unitDir, 'agent-team-worker.service.d');
  const dashboardDropinDir = path.join(unitDir, 'agent-team-dashboard.service.d');
  for (const dir of [configDir, unitDir, dropinDir, dashboardDropinDir]) inspect(dir, true);
  const worker = json(path.join(configDir, 'worker.json'));
  if (!worker.projects || typeof worker.projects !== 'object' || Array.isArray(worker.projects) || !Object.keys(worker.projects).length) throw new Error('worker.json must map project keys to checkouts');
  const envFile = path.join(configDir, 'service.env');
  if (readExisting(envFile) === null) throw new Error(`Missing ${envFile}; run install-local.mjs first`);
  if (readExisting(path.join(unitDir, 'agent-team-worker.service')) === null) throw new Error('Worker service unit is not installed');
  const key = validateKey(await keySource());
  // Validate every routed project against the live workspace before anything is written.
  const client = linear({ apiKey: key });
  for (const [projectId, checkout] of Object.entries(worker.projects)) {
    let manifest;
    try { manifest = JSON.parse(readFileSync(path.join(clean(checkout), '.agent-team.json'), 'utf8')); } catch { throw new Error(`Cannot read manifest for ${projectId}`); }
    if (manifest.queueProjectId !== projectId) throw new Error(`Manifest queueProjectId does not match ${projectId}`);
    validateIdeation(manifest.ideation);
    try { await client.context(manifest); } catch (error) { throw new Error(`Linear validation failed for ${projectId}: ${error.message}`); }
  }
  const linearEnv = path.join(configDir, 'linear.env');
  const intakeConfig = JSON.stringify({ coordinatorUrl: worker.coordinatorUrl ?? url, pollSeconds: 60, projects: worker.projects }, null, 2) + '\n';
  const unit = `# Generated by agent-team configure-linear.mjs v1\n[Unit]\nDescription=Agent team Linear intake\nAfter=agent-team-coordinator.service\n\n[Service]\nType=simple\nWorkingDirectory=${clean(toolkit).replaceAll('%', '%%')}\nEnvironmentFile=${envFile.replaceAll('%', '%%')}\nEnvironmentFile=${linearEnv.replaceAll('%', '%%')}\nEnvironment="AGENT_TEAM_URL=${url}"\nExecStart=${quote(nodePath, true)} ${quote(path.join(toolkit, 'core/intake.mjs'), true)} --config ${quote(path.join(configDir, 'intake.json'), true)}\nRestart=on-failure\nRestartSec=30\nUMask=0077\n`;
  const dropin = `# Generated by agent-team configure-linear.mjs v1\n[Service]\nEnvironmentFile=${linearEnv.replaceAll('%', '%%')}\n`;
  const files = [
    { file: linearEnv, contents: `LINEAR_API_KEY=${key}\n` },
    { file: path.join(configDir, 'intake.json'), contents: intakeConfig },
    { file: path.join(unitDir, 'agent-team-intake.service'), contents: unit },
    { file: path.join(dropinDir, 'linear.conf'), contents: dropin },
    // The dashboard posts owner conversations to Linear; it never passes the key to model runs.
    ...(readExisting(path.join(unitDir, 'agent-team-dashboard.service')) !== null ? [{ file: path.join(dashboardDropinDir, 'linear.conf'), contents: dropin }] : []),
  ].map(entry => ({ ...entry, previous: readExisting(entry.file) }));
  for (const entry of files) {
    if (entry.previous !== null && entry.previous !== entry.contents && !entry.file.endsWith('linear.env')) throw new Error(`Refusing to replace differing file: ${entry.file}`);
  }
  if (write) {
    privateDirectory(configDir);
    mkdirSync(dropinDir, { recursive: true, mode: 0o700 }); mkdirSync(dashboardDropinDir, { recursive: true, mode: 0o700 });
    for (const entry of files) atomicWrite(entry.file, entry.contents, entry.previous);
  }
  const paths = files.map(entry => entry.file);
  for (const file of paths) log(file);
  log('systemctl --user daemon-reload');
  log('systemctl --user restart agent-team-worker.service agent-team-dashboard.service');
  log('systemctl --user start agent-team-intake.service');
  return { paths, installed: write, projects: Object.keys(worker.projects) };
}

function promptHidden(question) {
  return new Promise((resolve, reject) => {
    const stdin = process.stdin;
    process.stderr.write(question);
    stdin.setRawMode(true); stdin.resume(); stdin.setEncoding('utf8');
    let value = '';
    const done = (error) => { stdin.setRawMode(false); stdin.pause(); stdin.off('data', onData); process.stderr.write('\n'); error ? reject(error) : resolve(value); };
    const onData = chunk => {
      for (const char of chunk) {
        if (char === '\r' || char === '\n') return done();
        if (char === '\u0003') return done(new Error('Canceled'));
        if (char === '\u007f' || char === '\b') value = value.slice(0, -1);
        else value += char;
      }
    };
    stdin.on('data', onData);
  });
}

async function keyFromCli({ keyFile }) {
  if (keyFile) {
    if (!path.isAbsolute(keyFile) || !inspect(keyFile)) throw new Error('--key-file must be an existing absolute private file');
    return readExisting(keyFile);
  }
  if (process.stdin.isTTY) return promptHidden('Linear API key (input hidden): ');
  let text = '';
  for await (const chunk of process.stdin) text += chunk;
  return text;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  Promise.resolve().then(() => {
    const options = parseArgs(process.argv.slice(2));
    return configure({ install: options.install === true, keySource: () => keyFromCli(options) });
  }).catch(error => { console.error(error.message); process.exitCode = 1; });
}
